# Configuration for ACT training on Flatland driving data

# Data settings
data:
  h5_file_path: "human_data/human_data_250928.h5"
  train_split: 0.8
  split_seed: 42  # Random seed for reproducible train/val episode splits

# Model architecture
model:
  action_dim: 9
  chunk_size: 32
  hidden_dim: 128
  nhead: 8
  num_encoder_layers: 4
  num_decoder_layers: 6
  dim_feedforward: 256
  dropout: 0.1
  spatial_size: 8
  # CVAE settings
  use_cvae: false
  latent_dim: 32

# Training parameters
training:
  epochs: 200
  batch_size: 128
  lr: 1e-4
  weight_decay: 1e-4
  num_workers: 0
  # CVAE loss weight
  kl_weight: 1.0
  # Focal loss parameters to handle class imbalance
  focal_alpha: 1.0
  focal_gamma: 2.0

# Logging and checkpoints
logging:
  output_dir: "outputs_act"
  save_interval: 5  # Save checkpoint every N epochs

# Run configuration
run_name: null  # If null, will use current timestamp

# Performance monitoring
enable_timer: false  # Enable detailed timing reports

# Hydra settings
hydra:
  run:
    dir: outputs/act_training/${now:%Y-%m-%d_%H-%M-%S}
