# @package _global_

# Hydra config for flat.py RL experiment

# Environment
env:
  view_size: 64
  dt: 0.1
  a_max: 2.0
  v_max: 5.0
  w_col: 1.0
  R_goal: 50.0
  disk_radius: 2.0
  render_dir: ${hydra:run.dir}/viz
  video_fps: 30
  w_dist: 50.0
  w_accel: 0.1
  save_viz: true
  render_every: 1  # Render every N episodes
  hitwall_cost: -100.0
  pyramid_scales: [1, 4, 16]
  num_levels: 3
  min_start_goal_dist: 5   # Minimum allowed distance between start and goal
  max_start_goal_dist: 30  # Maximum allowed distance between start and goal

# Training
train:
  replay_size: 10000
  gamma: 0.99
  tau: 0.005
  alpha: 0.05
  batch_size: 32
  warmup: 1000
  episodes: 500
  max_steps: 2000
  save_every: 50
  lr: 0.003
  use_amp: false

# Logging
log_dir: ${hydra:run.dir}/tb
run_name: ${now:%Y-%m-%d_%H-%M-%S}

# Seed
seed: 42

output_dir: outputs

# Model selection
model:
  type: conv   # Options: 'vit' or 'conv'
  vit_embed_dim: 128
  conv_out_dim: 384
