# @package _global_

# Hydra config for flat.py RL experiment

# Environment
env:
  num_envs: 32
  view_size: 64
  dt: 0.1
  a_max: 2.0
  v_max: 5.0
  w_col: 1.0
  R_goal: 100.0
  disk_radius: 2.0
  render_dir: ${hydra:run.dir}/viz
  video_fps: 30
  w_dist: 5.0
  w_accel: 0.1
  save_viz: true
  render_every: 10  # Render every N episodes
  render_env_ids: [0, 5]
  hitwall_cost: -50.0
  pyramid_levels: [0, 2, 4]  # 2^0=1, 2^2=4, 2^4=16
  num_levels: 3
  curriculum:
    - min_start_goal_dist: 10
      max_start_goal_dist: 20
      hitwall_cost: -10.0
      until_rollout: 50
    - min_start_goal_dist: 20
      max_start_goal_dist: 50
      hitwall_cost: -20.0
      until_rollout: 100
    - min_start_goal_dist: 30
      max_start_goal_dist: 100
      hitwall_cost: -30.0
      until_rollout: 300
    - min_start_goal_dist: 50
      max_start_goal_dist: 200
      hitwall_cost: -50.0
      until_rollout: 999999

# Training
train:
  resume: true
  lr: 3e-4
  gamma: 0.999
  gae_lambda: 0.99
  rollout_steps: 2048
  ppo_epochs: 4
  minibatch_size: 128
  clip_eps: 0.2
  max_steps: 2000
  save_every: 5
  num_rollouts: 2000 
  fp16: false


# Logging
log_dir: ${hydra:run.dir}/tb
run_name: ${now:%Y-%m-%d_%H-%M-%S}
enable_timer: true

# Seed
seed: 42

output_dir: outputs

# Model selection
model:
  type: conv   # Options: 'vit' or 'conv'
  vit_embed_dim: 128
  conv_out_dim: 384

# Debug and snapshot loading
load_actor_path: null
load_critic_path: null
