# @package _global_

# Hydra config for flat.py RL experiment

# Environment
env:
  vector_type: "async" # sync or async
  num_envs: 16
  view_size: 64
  dt: 0.1
  a_max: 2.0
  v_max: 5.0
  w_col: 1.0
  R_goal: 100.0
  disk_radius: 2.0
  render_dir: ${hydra:run.dir}/viz
  video_fps: 30
  w_dist: 5.0
  w_accel: 0.1
  save_viz: true
  render_every: 5  # Render every N episodes
  hitwall_cost: -50.0
  pyramid_scales: [1, 4, 16]
  num_levels: 3
  min_start_goal_dist: 20   # Minimum allowed distance between start and goal
  max_start_goal_dist: 150  # Maximum allowed distance between start and goal

# Training
train:
  resume: true
  lr: 0.0005
  gamma: 0.99
  gae_lambda: 0.95
  rollout_steps: 2048
  ppo_epochs: 4
  minibatch_size: 64
  clip_eps: 0.2
  episodes: 500
  max_steps: 2000
  save_every: 10
  num_rollouts: 1000 

# Logging
log_dir: ${hydra:run.dir}/tb
run_name: ${now:%Y-%m-%d_%H-%M-%S}

# Seed
seed: 42

output_dir: outputs

# Model selection
model:
  type: conv   # Options: 'vit' or 'conv'
  vit_embed_dim: 128
  conv_out_dim: 384

# Debug and snapshot loading
load_actor_path: null
load_critic_path: null
